# Generated by Django 4.1.7 on 2023-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_depart",
                    models.CharField(help_text="Nome do Departamento", max_length=100),
                ),
            ],
        ),
    ]
